import type { NextPage } from 'next'
import Head from 'next/head'
import { useId, useState } from 'react'
import PokemonImage from '../components/PokemonImage/PokemonImage'
import style from '../styles/hab.module.sass'


const Home: NextPage = () => {
  const id = useId();
  const [pkmName, setPkmName] = useState('');
  const [response, setResponse] = useState({
    name: '',
    sprites: {
      front_default: '',
    }
  });

  function searchApi() {
    fetch(`https://pokeapi.co/api/v2/pokemon/${pkmName}`)
      .then(res => res.json())
      .then(data => {
        setResponse(data);
        console.log(data);
      }
      )
  }

  return (
    <div>
      <Head>
        <title>Next Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.white}>
        <h1>Index</h1>
        <label htmlFor={id + 'pkmInputId'}>
          Enter Pókemon Name:
        </label>
        <input
          id={id + 'pkmInputId'}
          type="text"
          onChange={(e) => setPkmName(e.target.value)}
        />
        <button
          onClick={() => searchApi()}
        >
          Search
        </button>
        <p>{response.name}</p>

        <PokemonImage sprite={response.sprites.front_default} />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
